baseURL: 'https://marta.peeps.pt/'
languageCode: 'en-us'
title: 'SteviaMama'
theme: 'ananke'
sectionPagesMenu: main

DefaultContentLanguage: 'en'
SectionPagesMenu: 'main'
Paginate: 8 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics: ''
enableRobotsTXT: true

params:
  text_color: ''
  author: 'Marta Quintão'
  favicon: ''
  site_logo: 'logo.svg'
  description: 'The last theme you will ever need. Maybe.'
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class: "bg-moon-gray"
  recent_posts_number: 5
  body_classes: "avenir bg-near-white"
  text_color: "black"
  ananke_socials:
  - name: twitter
    url: https://twitter.com/theNewDynamic
  - name: github
    url: https://github.com/theNewDynamic

menu:
  main:
  - identifier: blog
    name: Blog
    title: Blog
    url: /blog/
    weight: 10
  - identifier: cookingmama
    name: Cooking Mama
    title: Cooking Mama
    url: /cookingmama/
    weight: 12
  - identifier: shoppingmama
    name: Shopping Mama
    title: CookingShopping Mama
    url: /shoppingmama/
    weight: 15
  - identifier: search
    name: Search
    title: Search
    url: /search/
    weight: 20
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 30

outputs:
  home: [HTML, RSS, JSON]

deployment:
  targets:
  - name: production
    URL: "s3://marta.peeps.pt?region=eu-west-1"
    cloudFrontDistributionID: ETYKTO7NYOPJE
  matchers:
  - pattern: "^.+\\.(js|css|svg|ttf)$"
    cacheControl: "max-age=31536000, no-transform, public"
    gzip: true
  - pattern: "^.+\\.(png|jpg|svg)$"
    cacheControl: "max-age=31536000, no-transform, public"
    gzip: false
  - pattern: "^sitemap\\.xml$"
    contentType: "application/xml"
    gzip: true
  - pattern: "^.+\\.(html|xml|json)$"
    gzip: true
